/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PotlucksImport } from './routes/potlucks'
import { Route as PeopleImport } from './routes/people'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PotlucksRoute = PotlucksImport.update({
  path: '/potlucks',
  getParentRoute: () => rootRoute,
} as any)

const PeopleRoute = PeopleImport.update({
  path: '/people',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleImport
      parentRoute: typeof rootRoute
    }
    '/potlucks': {
      id: '/potlucks'
      path: '/potlucks'
      fullPath: '/potlucks'
      preLoaderRoute: typeof PotlucksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/potlucks': typeof PotlucksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/potlucks': typeof PotlucksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/people': typeof PeopleRoute
  '/potlucks': typeof PotlucksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/people' | '/potlucks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/people' | '/potlucks'
  id: '__root__' | '/' | '/people' | '/potlucks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeopleRoute: typeof PeopleRoute
  PotlucksRoute: typeof PotlucksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeopleRoute: PeopleRoute,
  PotlucksRoute: PotlucksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/people",
        "/potlucks"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/people": {
      "filePath": "people.jsx"
    },
    "/potlucks": {
      "filePath": "potlucks.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
